# Анализ данных о стоимости автомобилей

## Задание

1. Загрузите данные.

2. Проверьте:
   - корректность загрузки данных;
   - наличие пропущенных значений;
   - типы данных переменных.

3. Создайте новый признак `company` (марка автомобиля).

4. Определите, автомобили каких производителей присутствуют в датасете.

5. Исправьте ошибки в названиях производителей и проверьте результат.

6. Оставьте необходимые предикторы и посчитайте корреляцию между переменной `price` и остальными признаками.

7. Преобразуйте категориальные переменные с помощью функции:

```python
pd.get_dummies()
```

8. Постройте линейную регрессионную модель с одним предиктором — `horsepower`.

9. Определите, какой процент изменчивости цены (`price`) объясняет полученная модель.

10. Постройте две дополнительные модели:
    - модель со всеми предикторами;
    - модель со всеми предикторами, кроме марки автомобиля (`company`).

11. Сравните модели:
    - значения `R²` и `Adjusted R²`;
    - коэффициенты регрессии;
    - статистическую значимость коэффициентов (`p-value`).

12. Сделайте вывод:
    - какая модель описывает данные лучше;
    - стоит ли оставлять информацию о марке автомобиля в модели.

13. Заполните пропуски в результатах и ответьте на поставленные вопросы.

In [1]:
import pandas as pd

In [2]:
cars = pd.read_csv('cars.csv')

In [4]:
cars.dtypes

car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [5]:
cars.isna().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [6]:
cars.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

## Создание признака `company`

Использовать полное название автомобиля не всегда удобно, поэтому создадим новый признак — марку автомобиля (`company`).

Для этого используйте столбец `CarName`, разделите значения по пробелу и сохраните первый элемент в новую колонку.

Пример:

```text
'audi 100 ls' → 'audi'
```

После создания нового признака:

1. Определите количество уникальных марок автомобилей в датасете.
2. Проверьте полученные значения и при необходимости исправьте ошибки в названиях производителей.
3. Удалите столбцы:
   - `CarName`
   - `car_ID`

Так как они не потребуются для дальнейшего анализа.

### Вопрос

Сколько уникальных марок автомобилей содержится в датасете?

In [9]:
cars['company'] = cars.CarName.str.split(' ').str[0]

In [10]:
cars.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,company
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,alfa-romero
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,alfa-romero
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,alfa-romero
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0,audi
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0,audi

In [11]:
cars.company.nunique()

28

In [12]:
cars = cars.drop(columns=['CarName', 'car_ID'])

In [13]:
cars.columns

Index(['symboling', 'fueltype', 'aspiration', 'doornumber', 'carbody',
       'drivewheel', 'enginelocation', 'wheelbase', 'carlength', 'carwidth',
       'carheight', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize',
       'fuelsystem', 'boreratio', 'stroke', 'compressionratio', 'horsepower',
       'peakrpm', 'citympg', 'highwaympg', 'price', 'company'],
      dtype='object')

## Очистка названий производителей

После создания признака `company` оказалось, что некоторые названия производителей содержат ошибки и дубликаты.

Исправьте значения следующим образом:

```text
'maxda'      → 'mazda'
'Nissan'     → 'nissan'
'porcshce'   → 'porsche'
'toyouta'    → 'toyota'
'vokswagen'  → 'volkswagen'
'vw'         → 'volkswagen'
```

После внесения исправлений повторно проверьте количество уникальных производителей.

### Вопрос

Сколько уникальных производителей автомобилей осталось в датасете после исправления ошибок?

In [14]:
cars.company.unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'maxda', 'mazda', 'buick', 'mercury',
       'mitsubishi', 'Nissan', 'nissan', 'peugeot', 'plymouth', 'porsche',
       'porcshce', 'renault', 'saab', 'subaru', 'toyota', 'toyouta',
       'vokswagen', 'volkswagen', 'vw', 'volvo'], dtype=object)

In [17]:
cars['company'] = cars.company.replace(to_replace={'maxda':'mazda', 'Nissan':'nissan', 'porcshce':'porsche', 'toyouta':'toyota','vokswagen':'volkswagen','vw' :'volkswagen'})

In [18]:
cars.company.nunique()

22

In [44]:
cols_to_keep = ['price', 'company', 'fueltype', 'aspiration','carbody', 
'drivewheel', 'wheelbase', 'carlength','carwidth', 
'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 
'boreratio','horsepower']

In [45]:
cars.corr(numeric_only=True)

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
symboling,1.000000,-0.531954,-0.357612,-0.232919,-0.541038,-0.227691,-0.105790,-0.130051,-0.008735,-0.178515,0.070873,0.273606,-0.035823,0.034606,-0.079978
wheelbase,-0.531954,1.000000,0.874587,0.795144,0.589435,0.776386,0.569329,0.488750,0.160959,0.249786,0.353294,-0.360469,-0.470414,-0.544082,0.577816
carlength,-0.357612,0.874587,1.000000,0.841118,0.491029,0.877728,0.683360,0.606454,0.129533,0.158414,0.552623,-0.287242,-0.670909,-0.704662,0.682920
carwidth,-0.232919,0.795144,0.841118,1.000000,0.279210,0.867032,0.735433,0.559150,0.182942,0.181129,0.640732,-0.220012,-0.642704,-0.677218,0.759325
carheight,-0.541038,0.589435,0.491029,0.279210,1.000000,0.295572,0.067149,0.171071,-0.055307,0.261214,-0.108802,-0.320411,-0.048640,-0.107358,0.119336
curbweight,-0.227691,0.776386,0.877728,0.867032,0.295572,1.000000,0.850594,0.648480,0.168790,0.151362,0.750739,-0.266243,-0.757414,-0.797465,0.835305
enginesize,-0.105790,0.569329,0.683360,0.735433,0.067149,0.850594,1.000000,0.583774,0.203129,0.028971,0.809769,-0.244660,-0.653658,-0.677470,0.874145
boreratio,-0.130051,0.488750,0.606454,0.559150,0.171071,0.648480,0.583774,1.000000,-0.055909,0.005197,0.573677,-0.254976,-0.584532,-0.587012,0.553173
stroke,-0.008735,0.160959,0.129533,0.182942,-0.055307,0.168790,0.203129,-0.055909,1.000000,0.186110,0.080940,-0.067964,-0.042145,-0.043931,0.079443
compressionratio,-0.178515,0.249786,0.158414,0.181129,0.261214,0.151362,0.028971,0.005197,0.186110,1.000000,-0.204326,-0.435741,0.324701,0.265201,0.067984
horsepower,0.070873,0.353294,0.552623,0.640732,-0.108802,0.750739,0.809769,0.573677,0.080940,-0.204326,1.000000,0.131073,-0.801456,-0.770544,0.808139
peakrpm,0.273606,-0.360469,-0.287242,-0.220012,-0.320411,-0.266243,-0.244660,-0.254976,-0.067964,-0.435741,0.131073,1.000000,-0.113544,-0.054275,-0.085267
citympg,-0.035823,-0.470414,-0.670909,-0.642704,-0.048640,-0.757414,-0.653658,-0.584532,-0.042145,0.324701,-0.801456,-0.113544,1.000000,0.971337,-0.685751
highwaympg,0.034606,-0.544082,-0.704662,-0.677218,-0.107358,-0.797465,-0.677470,-0.587012,-0.043931,0.265201,-0.770544,-0.054275,0.971337,1.000000,-0.697599
price,-0.079978,0.577816,0.682920,0.759325,0.119336,0.835305,0.874145,0.553173,0.079443,0.067984,0.808139,-0.085267,-0.685751,-0.697599,1.000000

In [46]:
df_dummy = pd.get_dummies(data=cars[cols_to_keep], drop_first=True)

In [47]:
df_dummy.head()

,price,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,company_audi,company_bmw,...,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor,cylindernumber_five,cylindernumber_four,cylindernumber_six,cylindernumber_three,cylindernumber_twelve,cylindernumber_two
0,13495.0,88.6,168.8,64.1,2548,130,3.47,111,False,False,...,False,False,False,False,False,True,False,False,False,False
1,16500.0,88.6,168.8,64.1,2548,130,3.47,111,False,False,...,False,False,False,False,False,True,False,False,False,False
2,16500.0,94.5,171.2,65.5,2823,152,2.68,154,False,False,...,False,False,True,False,False,False,True,False,False,False
3,13950.0,99.8,176.6,66.2,2337,109,3.19,102,True,False,...,True,False,False,False,False,True,False,False,False,False
4,17450.0,99.4,176.6,66.4,2824,136,3.19,115,True,False,...,True,False,False,False,True,False,False,False,False,False

In [48]:
import statsmodels.formula.api as smf
formula = 'price ~ horsepower'
smf.ols(formula, df_dummy).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.653
Model:                            OLS   Adj. R-squared:                  0.651
Method:                 Least Squares   F-statistic:                     382.2
Date:                Wed, 03 Jun 2026   Prob (F-statistic):           1.48e-48
Time:                        16:33:14   Log-Likelihood:                -2024.0
No. Observations:                 205   AIC:                             4052.
Df Residuals:                     203   BIC:                             4059.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -3721.7615    929.849     -4.003      0.000   -5555.163   -1888.360
horsepower   163.2631      8.351     19.549      0.000     146.796     179.730
==============================================================================
Omnibus:                       47.741   Durbin-Watson:                   0.792
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               91.702
Skew:                           1.141   Prob(JB):                     1.22e-20
Kurtosis:                       5.352   Cond. No.                         314.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [49]:
import statsmodels.api as sm

In [77]:
cols_to_keep_without_price = ['company', 'fueltype', 'aspiration','carbody', 
'drivewheel', 'wheelbase', 'carlength','carwidth', 
'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 
'boreratio','horsepower']

In [78]:
X = df_dummy.drop(columns='price')
y = df_dummy['price']

In [79]:
df_dummy = df_dummy.astype(float)

In [85]:
model_sklrn = sm.OLS(endog=y, exog=X).fit()
model_sklrn.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.989
Model:                            OLS   Adj. R-squared (uncentered):              0.985
Method:                 Least Squares   F-statistic:                              300.8
Date:                Wed, 03 Jun 2026   Prob (F-statistic):                   2.09e-133
Time:                        16:57:42   Log-Likelihood:                         -1809.7
No. Observations:                 205   AIC:                                      3711.
Df Residuals:                     159   BIC:                                      3864.
Df Model:                          46
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
wheelbase               136.4413     77.983      1.750      0.082     -17.574     290.457
carlength              -110.4333     50.120     -2.203      0.029    -209.419     -11.447
carwidth                272.7002    117.376      2.323      0.021      40.884     504.517
curbweight                5.3896      1.565      3.443      0.001       2.298       8.481
enginesize               63.9099     24.197      2.641      0.009      16.120     111.700
boreratio             -4936.4670   1789.529     -2.759      0.006   -8470.780   -1402.154
horsepower               41.7665     18.270      2.286      0.024       5.683      77.850
company_audi           1004.1792   2168.330      0.463      0.644   -3278.264    5286.623
company_bmw            7983.1395   2155.851      3.703      0.000    3725.343    1.22e+04
company_buick          3660.9604   2530.569      1.447      0.150   -1336.904    8658.825
company_chevrolet     -2192.5070   2103.557     -1.042      0.299   -6347.024    1962.010
company_dodge         -3176.5907   1726.269     -1.840      0.068   -6585.965     232.783
company_honda         -2339.0666   1661.221     -1.408      0.161   -5619.973     941.839
company_isuzu         -1303.9955   1858.734     -0.702      0.484   -4974.988    2366.997
company_jaguar         2846.5143   2607.093      1.092      0.277   -2302.484    7995.513
company_mazda          -754.7700   1682.149     -0.449      0.654   -4077.008    2567.468
company_mercury       -1726.6988   2831.257     -0.610      0.543   -7318.420    3865.022
company_mitsubishi    -3622.8853   1689.594     -2.144      0.034   -6959.827    -285.943
company_nissan        -1429.5470   1601.109     -0.893      0.373   -4591.731    1732.637
company_peugeot        -811.8027   1722.234     -0.471      0.638   -4213.208    2589.602
company_plymouth      -3191.7589   1710.404     -1.866      0.064   -6569.799     186.282
company_porsche        6373.5580   2820.405      2.260      0.025     803.269    1.19e+04
company_renault       -2059.8576   2104.615     -0.979      0.329   -6216.463    2096.748
company_saab            974.4934   1808.062      0.539      0.591   -2596.423    4545.410
company_subaru        -8467.5054   3321.774     -2.549      0.012    -1.5e+04   -1907.015
company_toyota        -2467.8809   1575.655     -1.566      0.119   -5579.793     644.031
company_volkswagen    -2016.9997   1643.418     -1.227      0.222   -5262.743    1228.744
company_volvo          1162.5472   1953.613      0.595      0.553   -2695.830    5020.925
fueltype_gas           -578.2480    922.963     -0.627      0.532   -2401.096    1244.600
aspiration_turbo        462.5828    691.293      0.669      0.504    -902.719    1827.885
carbody_hardtop       -2247.9581   1238.576     -1.815      0.071   -4694.141     198.224
carbody_hatchback     -2771.2066   1129.787     -2.453      0.015   -5002.532    -539.882
carbody_sedan         -1980.1532   1178.913     -1.680      0.095   -4308.502     348.196
carbody_wagon         -2719.1752   1252.184     -2.172      0.031   -5192.233    -246.117
drivewheel_fwd          477.7024    881.993      0.542      0.589   -1264.230    2219.635
drivewheel_rwd          650.8195   1054.816      0.617      0.538   -1432.439    2734.078
enginetype_dohcv      -9707.5281   4405.788     -2.203      0.029   -1.84e+04   -1006.114
enginetype_l          -1538.7705   1632.593     -0.943      0.347   -4763.135    1685.594
enginetype_ohc          -69.0261   1086.877     -0.064      0.949   -2215.603    2077.551
enginetype_ohcf        8009.7455   2618.820      3.059      0.003    2837.587    1.32e+04
enginetype_ohcv       -2608.6295   1241.674     -2.101      0.037   -5060.931    -156.328
enginetype_rotor       -773.3844   2124.559     -0.364      0.716   -4969.381    3422.612
cylindernumber_five   -6070.9626   2942.606     -2.063      0.041   -1.19e+04    -259.327
cylindernumber_four   -5600.4794   3569.945     -1.569      0.119   -1.27e+04    1450.149
cylindernumber_six    -7228.6546   2619.952     -2.759      0.006   -1.24e+04   -2054.260
cylindernumber_three   -726.9678   2724.595     -0.267      0.790   -6108.032    4654.096
cylindernumber_twelve -9921.1765   3649.261     -2.719      0.007   -1.71e+04   -2713.899
cylindernumber_two     -773.3844   2124.559     -0.364      0.716   -4969.381    3422.612
==============================================================================
Omnibus:                       72.615   Durbin-Watson:                   1.428
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              369.512
Skew:                           1.266   Prob(JB):                     5.77e-81
Kurtosis:                       9.071   Cond. No.                     1.01e+16
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The smallest eigenvalue is 1.37e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [86]:
X_1 = df_dummy[['wheelbase','carlength','carwidth','curbweight','enginesize','boreratio','horsepower']]

In [87]:
model_sklrn = sm.OLS(endog=y, exog=X_1).fit()
model_sklrn.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.950
Model:                            OLS   Adj. R-squared (uncentered):              0.949
Method:                 Least Squares   F-statistic:                              541.2
Date:                Wed, 03 Jun 2026   Prob (F-statistic):                   2.20e-125
Time:                        17:02:14   Log-Likelihood:                         -1960.9
No. Observations:                 205   AIC:                                      3936.
Df Residuals:                     198   BIC:                                      3959.
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
wheelbase    109.5689    100.538      1.090      0.277     -88.694     307.832
carlength    -55.2873     55.681     -0.993      0.322    -165.091      54.516
carwidth    -167.8983    127.816     -1.314      0.191    -419.954      84.157
curbweight     5.1339      1.386      3.703      0.000       2.400       7.868
enginesize    84.3889     13.006      6.489      0.000      58.742     110.036
boreratio  -1979.6726   1201.015     -1.648      0.101   -4348.095     388.750
horsepower    56.8679     12.956      4.389      0.000      31.318      82.418
==============================================================================
Omnibus:                       21.473   Durbin-Watson:                   0.771
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               45.968
Skew:                           0.483   Prob(JB):                     1.04e-10
Kurtosis:                       5.109   Cond. No.                     1.28e+04
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 1.28e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [93]:
df_without_company = df_dummy.loc[:, ~df_dummy.columns.str.startswith('company_')]

X = df_without_company.drop(columns='price')
y = df_without_company['price']

X = sm.add_constant(X)

model = sm.OLS(y, X).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.914
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     72.32
Date:                Wed, 03 Jun 2026   Prob (F-statistic):           9.86e-81
Time:                        17:13:48   Log-Likelihood:                -1881.6
No. Observations:                 205   AIC:                             3817.
Df Residuals:                     178   BIC:                             3907.
Df Model:                          26
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                   -1.7e+04    1.3e+04     -1.309      0.192   -4.26e+04    8625.219
wheelbase                71.1868     87.028      0.818      0.414    -100.552     242.925
carlength               -51.3497     50.341     -1.020      0.309    -150.692      47.993
carwidth                541.8700    253.327      2.139      0.034      41.958    1041.782
curbweight                2.9577      1.796      1.647      0.101      -0.585       6.501
enginesize               36.0515     22.376      1.611      0.109      -8.105      80.208
boreratio             -2230.4519   1731.681     -1.288      0.199   -5647.719    1186.815
horsepower               86.8164     16.717      5.193      0.000      53.827     119.806
fueltype_gas          -2423.0935    975.579     -2.484      0.014   -4348.283    -497.904
aspiration_turbo      -1139.2334    787.230     -1.447      0.150   -2692.738     414.271
carbody_hardtop       -3728.0949   1519.366     -2.454      0.015   -6726.383    -729.807
carbody_hatchback     -4639.1279   1294.594     -3.583      0.000   -7193.855   -2084.401
carbody_sedan         -3337.7854   1356.075     -2.461      0.015   -6013.838    -661.732
carbody_wagon         -4315.4661   1465.089     -2.946      0.004   -7206.646   -1424.287
drivewheel_fwd          297.2402   1121.766      0.265      0.791   -1916.431    2510.912
drivewheel_rwd         1939.1594   1226.536      1.581      0.116    -481.263    4359.582
enginetype_dohcv      -1.713e+04   4540.120     -3.773      0.000   -2.61e+04   -8171.142
enginetype_l           2176.0521   1332.818      1.633      0.104    -454.106    4806.211
enginetype_ohc         4006.5687    897.437      4.464      0.000    2235.584    5777.553
enginetype_ohcf        5421.2822   1388.078      3.906      0.000    2682.076    8160.488
enginetype_ohcv       -5001.2242   1345.435     -3.717      0.000   -7656.280   -2346.169
enginetype_rotor      -5196.6413   2084.532     -2.493      0.014   -9310.217   -1083.066
cylindernumber_five   -1.389e+04   2891.599     -4.802      0.000   -1.96e+04   -8180.353
cylindernumber_four   -1.618e+04   3243.610     -4.989      0.000   -2.26e+04   -9780.800
cylindernumber_six    -1.175e+04   2287.516     -5.135      0.000   -1.63e+04   -7231.547
cylindernumber_three  -9264.0553   4750.899     -1.950      0.053   -1.86e+04     111.279
cylindernumber_twelve -1.214e+04   3386.507     -3.585      0.000   -1.88e+04   -5458.378
cylindernumber_two    -5196.6413   2084.532     -2.493      0.014   -9310.217   -1083.066
==============================================================================
Omnibus:                       18.493   Durbin-Watson:                   1.249
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               50.728
Skew:                           0.293   Prob(JB):                     9.65e-12
Kurtosis:                       5.365   Cond. No.                     1.02e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""